display_cols = [
    "StayDate",
    "DOW",
    "SellingPrice",
    "OptimalPrice",
    "ProjRN_ChgAtOptimal",
    "ProjRevChgAtOptimal",
    "ProjOcc",
    "RoomsOTB",
    "TRN_RoomsOTB",
    "Pace_RoomsOTB",
    "Pace_TRN_RoomsOTB",
    "LYA_Occ",
    "",
]
