X_cols = [
    # 'StayDate',
    # 'AsOfDate',
    "week_of_year",
    "RoomsOTB",
    "RevOTB",
    "CxlForecast",
    "TRN_RoomsOTB",
    # "TRN_RevOTB",
    # 'TRN_CxlForecast',
    "WE",
    "DaysUntilArrival",
    "ADR_OTB",
    "SellingPrice",
    "RemSupply",
    "Mon",
    "Sat",
    "Sun",
    "Thu",
    "Tue",
    "Wed",
    "NONTRN_RoomsOTB",
    # "NONTRN_RevOTB",
    # "NONTRN_ADR_OTB",
    # "TRN_ADR_OTB",
    "TM30_RoomsPickup",
    # "TM30_RevPickup",
    # "TM30_ADR_Pickup",
    "TM30_TRN_RoomsPickup",
    # "TM30_TRN_RevPickup",
    # "TM30_TRN_ADR_Pickup",
    "TM30_NONTRN_RoomsPickup",
    # "TM30_NONTRN_RevPickup",
    # "TM30_NONTRN_ADR_Pickup",
    "TM15_RoomsPickup",
    # "TM15_RevPickup",
    # "TM15_ADR_Pickup",
    "TM15_TRN_RoomsPickup",
    # "TM15_TRN_RevPickup",
    # "TM15_TRN_ADR_Pickup",
    "TM15_NONTRN_RoomsPickup",
    # "TM15_NONTRN_RevPickup",
    # "TM15_NONTRN_ADR_Pickup",
    "TM05_RoomsPickup",
    # "TM05_RevPickup",
    # "TM05_ADR_Pickup",
    "TM05_TRN_RoomsPickup",
    # "TM05_TRN_RevPickup",
    # "TM05_TRN_ADR_Pickup",
    "TM05_NONTRN_RoomsPickup",
    # "TM05_NONTRN_RevPickup",
    # "TM05_NONTRN_ADR_Pickup",
    "Pace_RoomsOTB",
    # "Pace_ADR_OTB",
    # "Pace_RevOTB",
    # 'Pace_CxlForecast',
    "Pace_RemSupply",
    "Pace_SellingPrice",
    "Pace_TRN_RoomsOTB",
    # "Pace_TRN_ADR_OTB",
    # "Pace_TRN_RevOTB",
    "Pace_NONTRN_RoomsOTB",
    # "Pace_NONTRN_ADR_OTB",
    # "Pace_NONTRN_RevOTB",
    "Pace_TM30_RoomsPickup",
    # "Pace_TM30_ADR_Pickup",
    # "Pace_TM30_RevPickup",
    "Pace_TM30_TRN_RoomsPickup",
    # "Pace_TM30_TRN_ADR_Pickup",
    # "Pace_TM30_TRN_RevPickup",
    "Pace_TM30_NONTRN_RoomsPickup",
    # "Pace_TM30_NONTRN_ADR_Pickup",
    # "Pace_TM30_NONTRN_RevPickup",
    "Pace_TM15_RoomsPickup",
    # "Pace_TM15_ADR_Pickup",
    # "Pace_TM15_RevPickup",
    "Pace_TM15_TRN_RoomsPickup",
    # "Pace_TM15_TRN_ADR_Pickup",
    # "Pace_TM15_TRN_RevPickup",
    "Pace_TM15_NONTRN_RoomsPickup",
    # "Pace_TM15_NONTRN_ADR_Pickup",
    # "Pace_TM15_NONTRN_RevPickup",
    "Pace_TM05_RoomsPickup",
    # "Pace_TM05_ADR_Pickup",
    # "Pace_TM05_RevPickup",
    "Pace_TM05_TRN_RoomsPickup",
    # "Pace_TM05_TRN_ADR_Pickup",
    # "Pace_TM05_TRN_RevPickup",
    # "Pace_TM05_NONTRN_RoomsPickup",
    # "Pace_TM05_NONTRN_ADR_Pickup",
    # "Pace_TM05_NONTRN_RevPickup",
]

rf_cols = [
    # "AsOfDate",
    # "StayDate",
    "week_of_year",
    "RoomsOTB",
    "RoomsOTB_STLY",
    "RevOTB",
    "RevOTB_STLY",
    "CxlForecast",
    "TRN_RoomsOTB",
    "TRN_RoomsOTB_STLY",
    "TRN_RevOTB",
    "TRN_RevOTB_STLY",
    "TRN_CxlForecast",
    "WE",
    "DaysUntilArrival",
    "ADR_OTB",
    "SellingPrice",
    "RemSupply",
    "Mon",
    "Sat",
    "Sun",
    "Thu",
    "Tue",
    "Wed",
    "ACTUAL_RoomsPickup_STLY",
    "ACTUAL_ADR_Pickup_STLY",
    "ACTUAL_RevPickup_STLY",
    "ACTUAL_TRN_RoomsPickup_STLY",
    "ACTUAL_TRN_ADR_Pickup_STLY",
    "ACTUAL_TRN_RevPickup_STLY",
    "OTB_GapToLYA_RoomsSold",
    "OTB_GapToLYA_ADR",
    "OTB_GapToLYA_RoomRev",
    "OTB_GapToLYA_NumCancels",
    "OTB_GapToLYA_TRN_RoomsSold",
    "OTB_GapToLYA_TRN_ADR",
    "OTB_GapToLYA_TRN_RoomRev",
    "TRN_ADR_OTB",
    "TM30_RoomsPickup",
    "TM30_RevPickup",
    "TM30_ADR_Pickup",
    "TM30_TRN_RoomsPickup",
    "TM30_TRN_RevPickup",
    "TM30_TRN_ADR_Pickup",
    "TM15_RoomsPickup",
    "TM15_RevPickup",
    "TM15_ADR_Pickup",
    "TM15_TRN_RoomsPickup",
    "TM15_TRN_RevPickup",
    "TM15_TRN_ADR_Pickup",
    "TM05_RoomsPickup",
    "TM05_RevPickup",
    "TM05_ADR_Pickup",
    "TM05_TRN_RoomsPickup",
    "TM05_TRN_RevPickup",
    "TM05_TRN_ADR_Pickup",
    "Pace_RoomsOTB",
    "Pace_ADR_OTB",
    "Pace_RevOTB",
    "Pace_CxlForecast",
    "Pace_RemSupply",
    "Pace_SellingPrice",
    "Pace_TRN_RoomsOTB",
    "Pace_TRN_ADR_OTB",
    "Pace_TRN_RevOTB",
    "Pace_TM30_RoomsPickup",
    "Pace_TM30_ADR_Pickup",
    "Pace_TM30_RevPickup",
    "Pace_TM30_TRN_RoomsPickup",
    "Pace_TM30_TRN_ADR_Pickup",
    "Pace_TM30_TRN_RevPickup",
    "Pace_TM15_RoomsPickup",
    "Pace_TM15_ADR_Pickup",
    "Pace_TM15_RevPickup",
    "Pace_TM15_TRN_RoomsPickup",
    "Pace_TM15_TRN_ADR_Pickup",
    "Pace_TM15_TRN_RevPickup",
    "Pace_TM05_RoomsPickup",
    "Pace_TM05_ADR_Pickup",
    "Pace_TM05_RevPickup",
    "Pace_TM05_TRN_RoomsPickup",
    "Pace_TM05_TRN_ADR_Pickup",
    "Pace_TM05_TRN_RevPickup",
]