X_cols = [
    # 'StayDate',
    # 'AsOfDate',
    "WeekNum",
    "RoomsOTB",
    "RevOTB",
    "CxlForecast",
    "TRN_RoomsOTB",
    # "TRN_RevOTB",
    # 'TRN_CxlForecast',
    "WE",
    "DaysUntilArrival",
    "ADR_OTB",
    "SellingPrice",
    "RemSupply",
    "Mon",
    "Sat",
    "Sun",
    "Thu",
    "Tue",
    "Wed",
    "NONTRN_RoomsOTB",
    # "NONTRN_RevOTB",
    # "NONTRN_ADR_OTB",
    # "TRN_ADR_OTB",
    "TM30_RoomsPickup",
    # "TM30_RevPickup",
    # "TM30_ADR_Pickup",
    "TM30_TRN_RoomsPickup",
    # "TM30_TRN_RevPickup",
    # "TM30_TRN_ADR_Pickup",
    "TM30_NONTRN_RoomsPickup",
    # "TM30_NONTRN_RevPickup",
    # "TM30_NONTRN_ADR_Pickup",
    "TM15_RoomsPickup",
    # "TM15_RevPickup",
    # "TM15_ADR_Pickup",
    "TM15_TRN_RoomsPickup",
    # "TM15_TRN_RevPickup",
    # "TM15_TRN_ADR_Pickup",
    "TM15_NONTRN_RoomsPickup",
    # "TM15_NONTRN_RevPickup",
    # "TM15_NONTRN_ADR_Pickup",
    "TM05_RoomsPickup",
    # "TM05_RevPickup",
    # "TM05_ADR_Pickup",
    "TM05_TRN_RoomsPickup",
    # "TM05_TRN_RevPickup",
    # "TM05_TRN_ADR_Pickup",
    "TM05_NONTRN_RoomsPickup",
    # "TM05_NONTRN_RevPickup",
    # "TM05_NONTRN_ADR_Pickup",
    "RoomsGapToLYA",
    "RevGapToLYA",
    # "ADR_GapToLYA",
    "TRN_RoomsGapToLYA",
    "TRN_RevGapToLYA",
    # "TRN_ADR_GapToLYA",
    "NONTRN_RoomsGapToLYA",
    # "NONTRN_RevGapToLYA",
    # "NONTRN_ADR_GapToLYA",
    "RoomsOTB_Pace",
    # "ADR_OTB_Pace",
    # "RevOTB_Pace",
    # 'CxlForecast_Pace',
    "RemSupply_Pace",
    "SellingPrice_Pace",
    "TRN_RoomsOTB_Pace",
    # "TRN_ADR_OTB_Pace",
    # "TRN_RevOTB_Pace",
    "NONTRN_RoomsOTB_Pace",
    # "NONTRN_ADR_OTB_Pace",
    # "NONTRN_RevOTB_Pace",
    "TM30_RoomsPickup_Pace",
    # "TM30_ADR_Pickup_Pace",
    # "TM30_RevPickup_Pace",
    "TM30_TRN_RoomsPickup_Pace",
    # "TM30_TRN_ADR_Pickup_Pace",
    # "TM30_TRN_RevPickup_Pace",
    "TM30_NONTRN_RoomsPickup_Pace",
    # "TM30_NONTRN_ADR_Pickup_Pace",
    # "TM30_NONTRN_RevPickup_Pace",
    "TM15_RoomsPickup_Pace",
    # "TM15_ADR_Pickup_Pace",
    # "TM15_RevPickup_Pace",
    "TM15_TRN_RoomsPickup_Pace",
    # "TM15_TRN_ADR_Pickup_Pace",
    # "TM15_TRN_RevPickup_Pace",
    "TM15_NONTRN_RoomsPickup_Pace",
    # "TM15_NONTRN_ADR_Pickup_Pace",
    # "TM15_NONTRN_RevPickup_Pace",
    "TM05_RoomsPickup_Pace",
    # "TM05_ADR_Pickup_Pace",
    # "TM05_RevPickup_Pace",
    "TM05_TRN_RoomsPickup_Pace",
    # "TM05_TRN_ADR_Pickup_Pace",
    # "TM05_TRN_RevPickup_Pace",
    "TM05_NONTRN_RoomsPickup_Pace",
    # "TM05_NONTRN_ADR_Pickup_Pace",
    # "TM05_NONTRN_RevPickup_Pace",
]

rf_cols = [
    "AsOfDate",
    "StayDate",
    "WeekNum",
    "RoomsOTB",
    "RevOTB",
    "CxlForecast",
    "TRN_RoomsOTB",
    "TRN_RevOTB",
    "TRN_CxlForecast",
    "WE",
    "DaysUntilArrival",
    "ADR_OTB",
    "SellingPrice",
    "RemSupply",
    "Mon",
    "Sat",
    "Sun",
    "Thu",
    "Tue",
    "Wed",
    "NONTRN_RoomsOTB",
    "NONTRN_RevOTB",
    "NONTRN_ADR_OTB",
    "TRN_ADR_OTB",
    "TM30_RoomsPickup",
    "TM30_RevPickup",
    "TM30_ADR_Pickup",
    "TM30_TRN_RoomsPickup",
    "TM30_TRN_RevPickup",
    "TM30_TRN_ADR_Pickup",
    "TM30_NONTRN_RoomsPickup",
    "TM30_NONTRN_RevPickup",
    "TM30_NONTRN_ADR_Pickup",
    "TM15_RoomsPickup",
    "TM15_RevPickup",
    "TM15_ADR_Pickup",
    "TM15_TRN_RoomsPickup",
    "TM15_TRN_RevPickup",
    "TM15_TRN_ADR_Pickup",
    "TM15_NONTRN_RoomsPickup",
    "TM15_NONTRN_RevPickup",
    "TM15_NONTRN_ADR_Pickup",
    "TM05_RoomsPickup",
    "TM05_RevPickup",
    "TM05_ADR_Pickup",
    "TM05_TRN_RoomsPickup",
    "TM05_TRN_RevPickup",
    "TM05_TRN_ADR_Pickup",
    "TM05_NONTRN_RoomsPickup",
    "TM05_NONTRN_RevPickup",
    "TM05_NONTRN_ADR_Pickup",
    "RoomsGapToLYA",
    "RevGapToLYA",
    "ADR_GapToLYA",
    "TRN_RoomsGapToLYA",
    "TRN_RevGapToLYA",
    "TRN_ADR_GapToLYA",
    "NONTRN_RoomsGapToLYA",
    "NONTRN_RevGapToLYA",
    "NONTRN_ADR_GapToLYA",
    "RoomsOTB_Pace",
    "ADR_OTB_Pace",
    "RevOTB_Pace",
    "CxlForecast_Pace",
    "RemSupply_Pace",
    "SellingPrice_Pace",
    "TRN_RoomsOTB_Pace",
    "TRN_ADR_OTB_Pace",
    "TRN_RevOTB_Pace",
    "NONTRN_RoomsOTB_Pace",
    "NONTRN_ADR_OTB_Pace",
    "NONTRN_RevOTB_Pace",
    "TM30_RoomsPickup_Pace",
    "TM30_ADR_Pickup_Pace",
    "TM30_RevPickup_Pace",
    "TM30_TRN_RoomsPickup_Pace",
    "TM30_TRN_ADR_Pickup_Pace",
    "TM30_TRN_RevPickup_Pace",
    "TM30_NONTRN_RoomsPickup_Pace",
    "TM30_NONTRN_ADR_Pickup_Pace",
    "TM30_NONTRN_RevPickup_Pace",
    "TM15_RoomsPickup_Pace",
    "TM15_ADR_Pickup_Pace",
    "TM15_RevPickup_Pace",
    "TM15_TRN_RoomsPickup_Pace",
    "TM15_TRN_ADR_Pickup_Pace",
    "TM15_TRN_RevPickup_Pace",
    "TM15_NONTRN_RoomsPickup_Pace",
    "TM15_NONTRN_ADR_Pickup_Pace",
    "TM15_NONTRN_RevPickup_Pace",
    "TM05_RoomsPickup_Pace",
    "TM05_ADR_Pickup_Pace",
    "TM05_RevPickup_Pace",
    "TM05_TRN_RoomsPickup_Pace",
    "TM05_TRN_ADR_Pickup_Pace",
    "TM05_TRN_RevPickup_Pace",
    "TM05_NONTRN_RoomsPickup_Pace",
    "TM05_NONTRN_ADR_Pickup_Pace",
    "TM05_NONTRN_RevPickup_Pace",
]